name: Display Secret

on:
  push:
    branches:
      - main # プッシュがmainブランチに行われた場合にトリガーされる

jobs:
  display_secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Initialize Variable
        env:
          value_inc: 0
      - name: Initialize Variable Step 1
        run: |
          $((value_inc + 1))
          echo "value_inc=$value_inc"
