name: Display Secret

on:
  push:
    branches:
      - main # プッシュがmainブランチに行われた場合にトリガーされる

jobs:
  display_secret:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          value_inc=0
          echo "value_inc=$value_inc"
          value_inc=1
          echo "inc 1 --value_inc=$value_inc"
          ((value_inc++))
          echo "inc 2 --value_inc=$value_inc"
      - run: |
          ((value_inc++))
          echo "inc 3 --value_inc=$value_inc"
      - run: |
          ((value_inc++))
          echo "inc 4 --value_inc=$value_inc"
