name: Display Secret

on:
  push:
    branches:
      - main # プッシュがmainブランチに行われた場合にトリガーされる

jobs:
  display_secret:
    runs-on: ubuntu-latest
    env:
      VALUE_INC: 0
    steps:
      - name: Show Initial　Variable
        run: |
          echo "VALUE_INC　in Show Initial　Variable: $VALUE_INC"
      - name: Increment Variable Step 1
        run: |
          VALUE_INC=$((VALUE_INC + 1))
          echo "VALUE_INC in Increment Variable Step 1: $VALUE_INC"
      - name: Increment Variable Step 2
        run: |
          VALUE_INC=$((VALUE_INC + 1))
          echo "VALUE_INC in Increment Variable Step 2: $VALUE_INC"
