name: Display Secret

on:
  push:
    branches:
      - main # プッシュがmainブランチに行われた場合にトリガーされる

jobs:
  display_secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Initialize Variable
        run: |
          value_inc=0
          echo "value_inc=$value_inc"

      - name: Increment Variable Step 1
        run: |
          ((value_inc++))
          echo "inc 1 --value_inc=$value_inc"
