name: Increment_Value_Workflow

on:
  push:
    branches:
      - main # プッシュがmainブランチに行われた場合にトリガーされる echo "VALUE_INC=$tmp_val" >> $GITHUB_ENV

jobs:
  Increment_Value_Job:
    runs-on: ubuntu-latest
    #ステップ外に環境変数を定義し初期化 (ステップ外のenvでないと、ステップ内で使い回せない)
    env:
      VALUE_INC: 0
      #
      SECRET_MY_SECRET: ${{secrets.MY_SECRET}}
    steps:
      - name: Show Initial Val
        run: |
          #ステップ外環境変数をコンソール表示する 0のはず
          echo "env.VALUE_INC is ${{ env.VALUE_INC }}"
      - name: Increment Val Step 1
        run: | 
          #ステップ外環境変数を一時変数にコピー
          tmp_val=$((VALUE_INC))
          #一時変数をコンソール表示する 0のはず
          echo "tmp_val=${tmp_val}"
          #一時変数+1の値で、ステップ外環境変数VALUE_INCを更新する
          echo "VALUE_INC=$((tmp_val+1))" >> $GITHUB_ENV
      - name: Show Val Step 1
        run: |
          # 環境変数を一時変数にコピー
          t12_val=$((VALUE_INC))
          # 一時変数をコンソール表示 1のはず
          echo "VALUE_INC in Show Val Step 1: ${t12_val}"
      - name: Increment Val Step 2
        run: |
          #ステップ外環境変数+1の値を一時変数に格納
          t21_val=$((VALUE_INC+1))
          #一時変数のコンソール表示 2のはず
          echo "t21_val=${t21_val}"
          # ステップ外環境変数VALUE_INCを更新するけど変数はコンソール出力しない
          echo "VALUE_INC=$((t21_val))" >> $GITHUB_ENV 2>/dev/null
      - name: Show Val Step 2
        run: |
          t22_val=$((VALUE_INC))
          # コンソール出力は2のはず
          echo "VALUE_INC in Show Variable Step 2: $t22_val"
      - name: Increment Val Step 3
        run: |
          #ステップ外環境変数+1の値を一時変数に格納
          t31_val=$((VALUE_INC + 1))
          #コンソール出力は3のはず
          echo "VALUE_INC in Increment Variable Step 3: $t31_val"
          #一時変数+1=4がステップ外環境変数に更新される
          echo "VALUE_INC=$((t31_val + 1))" >> $GITHUB_ENV
          #前の処理のt22_valが読み出せるかどうか
          test_beforeval=$((t22_val))
          echo "test_beforeval=${test_beforeval}"
      - name: Show Val Step 3
        run: |
          t32_val=$((VALUE_INC))
          #コンソール出力は4のはず
          echo "VALUE_INC in Show Variable Step 3: $t32_val"
          #次のコンソール出力も4のはず
          echo "VALUE_INC in Show Variable Step 3: ${{ env.VALUE_INC }}"
  Secret_Reading_Test_Job:
    runs-on: ubuntu-latest
    #ステップ外に環境変数を定義し初期化 (ステップ外のenvでないと、ステップ内で使い回せない)
    env:
      SECRET_MY_SECRET: ${{secrets.MY_SECRET}}
    steps:
      - name: Direct Show Secret
        run: |
          tmpvalx=$((MY_SECRET))
          echo "Secret MY_Secret = $tmpvalx"
          echo "Secret MY_Secret = ${{secrets.MY_SECRET}}"
          echo "Secret env.SECRET_MY_SECRET = ${{env.SECRET_MY_SECRET}}"